-- CREO MI TABLA VICTIMA_VIRUS
CREATE TABLE victimas_virus (
    id_victima        		NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_victima    		VARCHAR2(50) NULL,
    apellido_victima  		VARCHAR2(50) NULL,
    direccion_victima 		VARCHAR2(200) NULL,
    fecha_primera_sospecha  DATE NULL,
    fecha_confirmacion		DATE NULL,
    fecha_muerte			DATE NULL,
	estado_victima			VARCHAR2(50) NULL
);

-- CREO MI TABLA TRATAMIENTO
CREATE TABLE tratamiento (
    id_tratamiento            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tratamiento               VARCHAR2(150) NULL,
    efectividad               INTEGER NULL
);

-- CREO MI TABLA HOSPITAL;
CREATE TABLE hospital (
    id_hospital             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE               	VARCHAR2(150) NULL,
    direccion               VARCHAR2(150) NULL
);
-- CREO MI TABLA CONTACTO;
CREATE TABLE contacto (
    id_contacto             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO 		          	VARCHAR2(150) NULL
    
);
-- CREO MI TABLA UBICACION;
CREATE TABLE ubicacion (
    id_ubicacion             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DIRECCION	          	 VARCHAR2(150) NULL
    
);
-- CREO MI TABLA ASOCIADO;
CREATE TABLE asociado(
	id_asociado 			NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	nombre_asociado    		VARCHAR2(50) NULL,
    apellido_asociado  		VARCHAR2(50) NULL

);
-- CREO MI TABLA VICTIMA_TRATAMIENTO;
CREATE TABLE victima_tratamiento(
	id_victima_tratamiento NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	efectividad_vic		   INTEGER NULL,
	fecha_ini_trat		   DATE NULL,
	fecha_fin_trat		   DATE NULL,
	id_victima 			   NUMBER(10),
	id_tratamiento 		   NUMBER(10),
	
	FOREIGN KEY (id_victima) REFERENCES victimas_virus(id_victima),
	FOREIGN KEY (id_tratamiento) REFERENCES tratamiento(id_tratamiento)
	
);
-- CREO MI TABLA VICTIMA_HOSPITAL;
CREATE TABLE victima_hospital(
	id_victima_hospital NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	fecha_llegada		   DATE,
	fecha_retiro		   DATE,
	id_victima 			   NUMBER(10),
	id_hospital 		   NUMBER(10),
	
	FOREIGN KEY (id_victima) REFERENCES victimas_virus(id_victima),
	FOREIGN KEY (id_hospital) REFERENCES hospital(id_hospital)
);
-- CREO MI TABLA VICTIMA_ASOCIADO
CREATE TABLE victima_asociado(
	id_victima_asociado 	NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	fecha_conocio		DATE,
	fecha_ini_cont 		DATE,
	fecha_fin_cont		DATE,
	id_victima    		NUMBER(10) NULL,
    id_asociado  		NUMBER(10) NULL,
    id_contacto			NUMBER(10) NULL,
    FOREIGN KEY (id_victima) REFERENCES victimas_virus(id_victima),
	FOREIGN KEY (id_asociado) REFERENCES asociado(id_asociado),
	FOREIGN KEY (id_contacto) REFERENCES contacto(id_contacto)

);
-- CREO MI TABLA VICTIMA_UBICACION;
CREATE TABLE victima_ubicacion(
	id_victima_ubicacion 	NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	id_victima    			NUMBER(10) NULL,
    id_ubicacion  			NUMBER(10) NULL,
    FOREIGN KEY (id_victima) REFERENCES victimas_virus(id_victima),
	FOREIGN KEY (id_ubicacion ) REFERENCES ubicacion(id_ubicacion )

);

-- Con esta consulta lleno mi tabla de VICTIMAS_VIRUS;
INSERT INTO VICTIMAS_VIRUS (NOMBRE_VICTIMA, APELLIDO_VICTIMA, DIRECCION_VICTIMA, FECHA_PRIMERA_SOSPECHA, FECHA_CONFIRMACION, FECHA_MUERTE, ESTADO_VICTIMA)
SELECT DISTINCT t.NOMBRE_VICTIMA , t.APELLIDO_VICTIMA ,t.DIRECCION_VICTIMA ,t.FECHA_PRIMERA_SOSPECHA , t.FECHA_CONFIRMACION , t.FECHA_MUERTE , t.ESTADO_VICTIMA 
FROM TEMPORAL t WHERE t.NOMBRE_VICTIMA IS NOT NULL AND t.APELLIDO_VICTIMA  IS NOT NULL ;


--SELECT COUNT(*) FROM VICTIMAS_VIRUS vv ;

-- Obtengo los tratamientos que existen. ;

INSERT INTO TRATAMIENTO (TRATAMIENTO, EFECTIVIDAD)
SELECT DISTINCT t.TRATAMIENTO , t.EFECTIVIDAD 
FROM TEMPORAL t WHERE T.TRATAMIENTO IS NOT NULL;

--SELECT COUNT(*) FROM TRATAMIENTO t2 ;

-- Obtengo los tipos de contacto que existen.;
INSERT INTO CONTACTO (CONTACTO.TIPO)
SELECT DISTINCT T.CONTACTO_FISICO FROM TEMPORAL t 
WHERE T.CONTACTO_FISICO IS NOT NULL;

-- Lleno mi tabla de hospital;
INSERT INTO HOSPITAL (NOMBRE,DIRECCION)
SELECT DISTINCT t.NOMBRE_HOSPITAL, t.DIRECCION_HOSPITAL  
FROM TEMPORAL t WHERE t.NOMBRE_HOSPITAL IS NOT NULL;

--SELECT COUNT(*) FROM HOSPITAL h ;

-- Lleno mi tabla de asociados;
INSERT INTO ASOCIADO a (a.NOMBRE_ASOCIADO,a.APELLIDO_ASOCIADO)
SELECT DISTINCT t.NOMBRE_ASOCIADO, t.APELLIDO_ASOCIADO FROM TEMPORAL t
WHERE t.NOMBRE_ASOCIADO IS NOT NULL AND t.APELLIDO_ASOCIADO IS NOT NULL;

-- lleno mi tabla de ubicacion;
INSERT INTO UBICACION (UBICACION.DIRECCION)
SELECT DISTINCT T.UBICACION_VICTIMA FROM TEMPORAL t  WHERE T.UBICACION_VICTIMA IS NOT NULL;


-- Lleno mi tabla de victima_tratamiento;
INSERT INTO VICTIMA_TRATAMIENTO (efectividad_vic,fecha_ini_trat	,fecha_fin_trat,id_victima,id_tratamiento)
SELECT DISTINCT T.EFECTIVIDAD_EN_VICTIMA , T.FECHA_INICIO_TRATAMIENTO, T.FECHA_FIN_TRATAMIENTO, VV.ID_VICTIMA , T2.ID_TRATAMIENTO   FROM TEMPORAL t 
JOIN VICTIMAS_VIRUS vv ON T.NOMBRE_VICTIMA = VV.NOMBRE_VICTIMA  AND T.APELLIDO_VICTIMA = VV.APELLIDO_VICTIMA
JOIN TRATAMIENTO t2 ON T2.TRATAMIENTO  = T.TRATAMIENTO ;

-- Lleno mi tabla victima_hospital;
INSERT INTO VICTIMA_HOSPITAL (FECHA_LLEGADA, FECHA_RETIRO,ID_VICTIMA,ID_HOSPITAL)
SELECT DISTINCT T.FECHA_LLEGADA ,T.FECHA_RETIRO, VV.ID_VICTIMA , H.ID_HOSPITAL   FROM TEMPORAL t 
JOIN VICTIMAS_VIRUS vv ON T.NOMBRE_VICTIMA = VV.NOMBRE_VICTIMA  AND T.APELLIDO_VICTIMA = VV.APELLIDO_VICTIMA
JOIN HOSPITAL h ON T.NOMBRE_HOSPITAL = H.NOMBRE 
WHERE T.FECHA_LLEGADA IS NOT NULL AND T.FECHA_RETIRO IS NOT NULL;

-- lleno mi tabla victima_asociado;

INSERT INTO VICTIMA_ASOCIADO va (va.ID_VICTIMA,va.ID_ASOCIADO, va.FECHA_CONOCIO, va.FECHA_INI_CONT, va.FECHA_FIN_CONT)
SELECT DISTINCT VV.ID_VICTIMA , A.ID_ASOCIADO , T.FECHA_CONOCIO, T.FECHA_INICIO_CONTACTO , T.FECHA_FIN_CONTACTO   FROM TEMPORAL t 
JOIN ASOCIADO a ON T.NOMBRE_ASOCIADO = A.NOMBRE_ASOCIADO AND T.APELLIDO_ASOCIADO = A.APELLIDO_ASOCIADO 
JOIN VICTIMAS_VIRUS vv ON T.NOMBRE_VICTIMA = VV.NOMBRE_VICTIMA  AND T.APELLIDO_VICTIMA = VV.APELLIDO_VICTIMA
JOIN CONTACTO c ON C.TIPO = T.CONTACTO_FISICO 
WHERE t.FECHA_CONOCIO IS NOT NULL  AND t.FECHA_INICIO_CONTACTO  IS NOT NULL AND t.FECHA_FIN_CONTACTO IS NOT NULL ;


-- Lleno mi tabla victima_ubicacion;
INSERT INTO VICTIMA_UBICACION vu (vu.ID_VICTIMA,vu.ID_UBICACION)
SELECT DISTINCT vv.ID_VICTIMA, u.ID_UBICACION  FROM TEMPORAL t 
JOIN VICTIMAS_VIRUS vv ON T.NOMBRE_VICTIMA = VV.NOMBRE_VICTIMA  AND T.APELLIDO_VICTIMA = VV.APELLIDO_VICTIMA
JOIN UBICACION u ON u.DIRECCION = t.UBICACION_VICTIMA ;
